name: "Steampipe GitHub Action"
author: "Turbot.com"
description: "Run Steampipe against Terraform infrastructure code, as a pre-packaged GitHub Action"

branding:
  color: "red"
  icon: "shield"

inputs:
  steampipe_version:
    description: "Steampipe version"
  connections:
    description: "The connection string"
    required: true

runs:
  using: composite
  steps:
    - name: Install Steampipe
      shell: bash
      run: |
        VER=${{ inputs.steampipe_version }}
        if [ "$VER" = "latest" ];then
          VER=""
        fi
        # Install Steampipe
        curl https://raw.githubusercontent.com/turbot/steampipe/main/install.sh | sudo bash -s $VER
        steampipe --version
        steampipe query "select 1"

    - name: Setup connections
      id: setup-connection
      shell: bash
      run: |
        printf '%s\n' '${{ inputs.connections }}' > $HOME/.steampipe/config/connections.spc

    - name: Install required plugins
      id: discover-plugins
      shell: bash
      run: |
        set +e
        output=$(steampipe plugin list 2>&1 1>/dev/null | grep -o 'steampipe plugin install [^$]*' | sed -E "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")
        plugins=$(echo $output | sed -E "s/steampipe plugin install //")
        eval $output
        echo "$plugins" | tr ' ' '\n' | while read word; do
            rm -f $HOME/.steampipe/config/*"$word"*
        done
        steampipe plugin list