name: "Steampipe GitHub Action"
author: "Turbot.com"
description: "Run Steampipe against Terraform infrastructure code, as a pre-packaged GitHub Action"

branding:
  color: "red"
  icon: "shield"

inputs:
  mod_url:
    description: "Git URL of specific terraform compliance mod that will be installed. This will be passed on to `git clone`"
    required: true
  steampipe_version:
    description: "The version number of Steampipe that will be installed"
    required: false
    default: ""
  run:
    description: "A list of benchmarks and controls to run (comma-separated). If no value is specified, it runs `check all`"
    required: false
    default: "all"
  path:
    description: "Directory with infrastructure code to scan explicitly, if not specified, it considers root of the repository as default"
    required: false
    default: "."
  github-token:
    description: "The token is used for fetching patch of a pull request to show only new issues"
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Install Steampipe
      shell: bash
      run: |
        # curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh -o /tmp/install_steampipe.sh
        # chmod +x /tmp/install_steampipe.sh
        # /tmp/install_steampipe.sh ${{ inputs.steampipe_version }}

        curl https://raw.githubusercontent.com/turbot/steampipe/main/install.sh | bash -s ${{ inputs.steampipe_version }}
        steampipe query "select 1"
    - name: Clone Mod
      shell: bash
      run: |
        git clone ${{ inputs.mod_url }}
    - name: Install and configure Terraform Plugin
      shell: bash
      run: |
        steampipe plugin install terraform
        # write config
        connection_data="
          connection \"terraform\" {
            plugin = \"terraform\"
            paths = [ \"${{inputs.path}}/**/*.tf\" ]
          }
        "

        # Write the config file
        printf '%s\n' "$connection_data" > "/home/steampipe/.steampipe/config/terraform.spc"
    - name: Get Mod
      shell: bash
      run: |
        mkdir /tmp/mod
        git clone --depth 1 "${{ inputs.mod_url }}" /tmp/mod
    - name: Run Check
      shell: bash
      run: |
        steampipe check "${{ inputs.run }}" --output=table --mod-location="/tmp/mod"
