name: "Steampipe GitHub Action"
author: "Turbot.com"
description: "Run Steampipe against Terraform infrastructure code, as a pre-packaged GitHub Action"

branding:
  color: "red"
  icon: "shield"

inputs:
  directory:
    description: "Directory with infrastructure code to scan. If not specified, it considers root of the repository as default"
    required: false
    default: "."
  # plugin:
  #   description: "The steampipe plugin that has to be installed"
  #   required: false
  version:
    description: "The steampipe version that has to be installed"
    required: false
    default: "latest"
outputs:
  steampipe-version:
    description: Exact version of Steampipe that was installed
runs:
  using: node16
  main: dist/index.js
