name: "Steampipe GitHub Action"
author: "Turbot.com"
description: "Run Steampipe against Terraform infrastructure code, as a pre-packaged GitHub Action"

branding:
  color: "red"
  icon: "shield"

inputs:
  mod_url:
    description: "Git URL of specific terraform compliance mod that will be installed. This will be passed on to `git clone`"
    required: true
  steampipe_version:
    description: "The version number of Steampipe that will be installed"
    required: false
    default: ""
  run:
    description: "A list of benchmarks and controls to run (space-separated). If no value is specified, it runs `check all`"
    required: false
    default: "all"
  path:
    description: "Directory with infrastructure code to scan explicitly, if not specified, it considers root of the repository as default"
    required: false
    default: "."
  github-token:
    description: "The token is used for fetching patch of a pull request to show only new issues"
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Install Steampipe
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/turbot/steampipe/main/install.sh | sudo bash -s ${{ inputs.steampipe_version }}
        mkdir -p /tmp/sp_install_dir
        steampipe query "select 1" --install-dir /tmp/sp_install_dir
    - name: Install and configure Terraform Plugin
      shell: bash
      run: |
        steampipe plugin install terraform --install-dir /tmp/sp_install_dir > /dev/null
        # write config
        connection_data="
          connection \"terraform\" {
            plugin = \"terraform\"
            paths = [ \"${{inputs.path}}/**/*.tf\" ]
          }
        "

        # Write the config file
        printf '%s\n' "$connection_data" > "/tmp/sp_install_dir/config/terraform.spc"
    - name: Get Mod
      shell: bash
      run: |
        mkdir /tmp/mod
        git clone --depth 1 "${{ inputs.mod_url }}" /tmp/mod
    - name: Run Check
      shell: bash
      run: |
        set +e
        steampipe check "${{ inputs.run }}" --output=none --mod-location="/tmp/mod" --export=json,md --install-dir=/tmp/sp_install_dir
        # ignore the 1 exit code which gets set if there are only alarms
        exit_code=$(echo $?)
        if [[ $exit_code -le 1 ]];then
          exit 0
        else
          exit $exit_code
        fi
    - name: Annotate
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js ${{ inputs.run }}
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
