on: [pull_request,push]

jobs:
  query_steampipe:
    runs-on: ubuntu-latest
    name: Run Steampipe queries
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Steampipe
        uses: ./ # Uses an action in the root directory
        id: setup-steampipe
        with:
          connections: |
            connection \"net\" {
              plugin = \"net\"
            }
          plugins: net
      - name: Run query
        shell: bash
        run: steampipe query "select issuer, not_after as exp_date from net_certificate where domain = 'steampipe.io'"